---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: list articles
      responses:
        '200':
          description: successful
    post:
      summary: create article
      responses:
        '200':
          description: successful
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      responses:
        '200':
          description: successful
    put:
      summary: update article
      responses:
        '200':
          description: successful
    delete:
      summary: delete article
      responses:
        '200':
          description: successful
  "/api/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
    post:
      summary: create category
      responses:
        '200':
          description: successful
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      responses:
        '200':
          description: successful
    patch:
      summary: update category
      responses:
        '200':
          description: successful
    put:
      summary: update category
      responses:
        '200':
          description: successful
    delete:
      summary: delete category
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
